using './main.bicep'

param location = 'koreacentral'
param environment = 'dev'
param dockerHubOrg = 'johnha97'
param imageTag = 'latest'
param postgresAdminUsername = 'fireiot_admin'
param postgresAdminPassword = 'YourSecurePassword123!'
param azureVisionEndpoint = 'https://fire-iot-ex.cognitiveservices.azure.com/'
param azureVisionKey = 'EkdGWlyVoOxsHxdvG2Bcqo23rtQtelSyZ1AcAwyIORE2PoMgNoGrJQQJ99BHACNns7RXJ3w3AAAFACOGa2W9'
