using './main.bicep'

param location = 'koreacentral'
param environment = 'dev'
param dockerHubOrg = 'johnha97'
param imageTag = 'latest'
param postgresAdminUsername = 'fireiot_admin'
param postgresAdminPassword = 'YourSecurePassword123!'
param azureVisionEndpoint = 'https://fire-iot.cognitiveservices.azure.com/'
param azureVisionKey = '1r73g9RL2qkraqun2lO4sxMv7Zdf5Y323Z1CcS7XuyBotp0MfKoaJQQJ99BHACNns7RXJ3w3AAAFACOGuAnM'
