using '../main.bicep'

param resourceGroupName = 'fire-iot-rg'
param location = 'eastus'
param environment = 'dev'
param dockerHubOrg = 'your-dockerhub-org'
param imageTag = 'latest'
param postgresConnectionString = 'postgresql://fireiot_user:password@fire-iot-postgres.postgres.database.azure.com:5432/core'
param redisConnectionString = 'redis://fire-iot-redis.redis.cache.windows.net:6380'
param eventHubConnectionString = 'Endpoint=sb://fire-iot-eventhub.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=key'
param otelEndpoint = 'https://fire-iot-appinsights.applicationinsights.azure.com/v2.1/traces'
